### ISSUE TITLE
Error on Windows 11

### ISSUE THREAD

**Issue by init5-SF** [itm4n/PrivescCheck#29] opened 2021-11-07 11:55 UTC
hey, I got this when I ran the latest version of the script (with and without -extended):

```
Get-ItemProperty : Specified cast is not valid.
At line:787 char:26
+ ... roperties = Get-ItemProperty -Path "Registry::$ServiceRegPath" -Error ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ItemProperty], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,Microsoft.PowerShell.Commands.GetItemPropertyCommand
```

Powershell 5.1
Windows 11 (21H2) 64bit

Let me know if more details are needed!
Cheers

**Comment by itm4n** [comment] 2021-11-11 08:27
Hi!
Thank you for reporting this issue. I haven't tested the script on Windows 11 yet to be honest.
But it looks like it will be more painful than I anticipated.

**Comment by itm4n** [comment] 2021-11-27 18:34
Hello,
I tested the script on a freshly installed Windows 11 VM and it runs very smoothly.
I think the problem you encountered is caused by a specific service configuration. It's not related to the version of the OS.
Therefore, I will need more information.
Maybe, if you use the `-Verbose` mode, you might be able to pinpoint exactly which service causes this error.

**Comment by itm4n** [comment] 2022-01-13 20:16
No news, closing the issue.

**Closed by itm4n** 2022-01-13 20:16 UTC
Labels: bug
